# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(15)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(170, 0, 471, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_ID = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_ID.setGeometry(QtCore.QRect(160, 100, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_ID.setFont(font)
        self.label_ID.setObjectName("label_ID")
        self.box_ID = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.box_ID.setGeometry(QtCore.QRect(260, 100, 341, 81))
        self.box_ID.setObjectName("box_ID")
        self.label_candidates = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_candidates.setGeometry(QtCore.QRect(180, 170, 471, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_candidates.setFont(font)
        self.label_candidates.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_candidates.setObjectName("label_candidates")
        self.radio_jane = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_jane.setGeometry(QtCore.QRect(330, 240, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio_jane.setFont(font)
        self.radio_jane.setObjectName("radio_jane")
        self.radio_john = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_john.setGeometry(QtCore.QRect(330, 300, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio_john.setFont(font)
        self.radio_john.setObjectName("radio_john")
        self.button_vote = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_vote.setGeometry(QtCore.QRect(190, 360, 411, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.button_vote.setFont(font)
        self.button_vote.setObjectName("button_vote")
        self.label_message = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_message.setGeometry(QtCore.QRect(80, 450, 651, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        self.label_message.setPalette(palette)
        self.label_message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_message.setObjectName("label_message")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voting Program"))
        self.label_title.setText(_translate("MainWindow", "VOTING APPLICATION"))
        self.label_ID.setText(_translate("MainWindow", "ID"))
        self.label_candidates.setText(_translate("MainWindow", "CANDIDATES"))
        self.radio_jane.setText(_translate("MainWindow", "JANE"))
        self.radio_john.setText(_translate("MainWindow", "JOHN"))
        self.button_vote.setText(_translate("MainWindow", "SUBMIT VOTE"))
        self.label_message.setText(_translate("MainWindow", "Already Voted"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
